In [1]:
import pandas as pd

In [2]:
df_test= pd.read_csv("test (1).csv")
df_test

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
0,2016-11-01 00:00:00.000 +0100,Mostly Cloudy,NaN,6.205556,4.527778,0.92,8.1466,297,0.0000,0,1021.74,Partly cloudy starting in the afternoon.
1,2016-11-01 01:00:00.000 +0100,Mostly Cloudy,NaN,5.827778,4.177778,0.92,7.7763,296,0.0000,0,1021.69,Partly cloudy starting in the afternoon.
2,2016-11-01 02:00:00.000 +0100,Partly Cloudy,NaN,5.311111,3.616667,0.93,7.6153,298,0.0000,0,1021.61,Partly cloudy starting in the afternoon.
3,2016-11-01 03:00:00.000 +0100,Partly Cloudy,NaN,4.800000,3.088889,0.94,7.3738,300,0.0000,0,1021.54,Partly cloudy starting in the afternoon.
4,2016-11-01 04:00:00.000 +0100,Clear,NaN,4.483333,2.883333,0.95,6.8103,303,0.0000,0,1021.54,Partly cloudy starting in the afternoon.
...,...,...,...,...,...,...,...,...,...,...,...,...
2180,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
2181,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
2182,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
2183,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
2184,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.

In [3]:
df_train = pd.read_csv("train (1).csv")
df_train

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
94263,2016-05-09 19:00:00.000 +0200,Partly Cloudy,rain,19.972222,19.972222,0.40,9.4668,42,16.1000,0,1018.11,Partly cloudy throughout the day.
94264,2016-05-09 20:00:00.000 +0200,Partly Cloudy,rain,17.816667,17.816667,0.46,3.8962,19,15.5526,0,1018.42,Partly cloudy throughout the day.
94265,2016-05-09 21:00:00.000 +0200,Partly Cloudy,rain,13.938889,13.938889,0.67,8.0500,70,16.1000,0,1019.21,Partly cloudy throughout the day.
94266,2016-05-09 22:00:00.000 +0200,Partly Cloudy,rain,12.733333,12.733333,0.77,8.0500,80,16.1000,0,1019.70,Partly cloudy throughout the day.
94267,2016-05-09 23:00:00.000 +0200,Partly Cloudy,rain,13.038889,13.038889,0.69,3.2039,75,15.1823,0,1019.45,Partly cloudy throughout the day.

In [4]:
df_test.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 374
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Cloud Cover                   0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [5]:
df_train.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 143
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Cloud Cover                   0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [6]:
df_test.nunique()

Formatted Date              2185
Summary                       10
Precip Type                    1
Temperature (C)             1583
Apparent Temperature (C)    1651
Humidity                      77
Wind Speed (km/h)            874
Wind Bearing (degrees)       331
Visibility (km)              522
Cloud Cover                    1
Pressure (millibars)        1076
Daily Summary                 32
dtype: int64

In [7]:
df_train.nunique()

Formatted Date              94244
Summary                        26
Precip Type                     2
Temperature (C)              7564
Apparent Temperature (C)     8981
Humidity                       90
Wind Speed (km/h)            2484
Wind Bearing (degrees)        360
Visibility (km)               935
Cloud Cover                     1
Pressure (millibars)         4979
Daily Summary                 207
dtype: int64

In [8]:
df_train[["Formatted Date","Temperature (C)"]]

                      Formatted Date  Temperature (C)
0      2006-04-01 00:00:00.000 +0200         9.472222
1      2006-04-01 01:00:00.000 +0200         9.355556
2      2006-04-01 02:00:00.000 +0200         9.377778
3      2006-04-01 03:00:00.000 +0200         8.288889
4      2006-04-01 04:00:00.000 +0200         8.755556
...                              ...              ...
94263  2016-05-09 19:00:00.000 +0200        19.972222
94264  2016-05-09 20:00:00.000 +0200        17.816667
94265  2016-05-09 21:00:00.000 +0200        13.938889
94266  2016-05-09 22:00:00.000 +0200        12.733333
94267  2016-05-09 23:00:00.000 +0200        13.038889

[94268 rows x 2 columns]

In [9]:
df_train["Formatted_Date"]=pd.to_datetime(df_train["Formatted Date"],utc=True)

In [10]:
df_train

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Formatted_Date
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.,2006-03-31 22:00:00+00:00
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.,2006-03-31 23:00:00+00:00
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.,2006-04-01 00:00:00+00:00
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.,2006-04-01 01:00:00+00:00
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.,2006-04-01 02:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94263,2016-05-09 19:00:00.000 +0200,Partly Cloudy,rain,19.972222,19.972222,0.40,9.4668,42,16.1000,0,1018.11,Partly cloudy throughout the day.,2016-05-09 17:00:00+00:00
94264,2016-05-09 20:00:00.000 +0200,Partly Cloudy,rain,17.816667,17.816667,0.46,3.8962,19,15.5526,0,1018.42,Partly cloudy throughout the day.,2016-05-09 18:00:00+00:00
94265,2016-05-09 21:00:00.000 +0200,Partly Cloudy,rain,13.938889,13.938889,0.67,8.0500,70,16.1000,0,1019.21,Partly cloudy throughout the day.,2016-05-09 19:00:00+00:00
94266,2016-05-09 22:00:00.000 +0200,Partly Cloudy,rain,12.733333,12.733333,0.77,8.0500,80,16.1000,0,1019.70,Partly cloudy throughout the day.,2016-05-09 20:00:00+00:00
94267,2016-05-09 23:00:00.000 +0200,Partly Cloudy,rain,13.038889,13.038889,0.69,3.2039,75,15.1823,0,1019.45,Partly cloudy throughout the day.,2016-05-09 21:00:00+00:00

In [11]:
df_train

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Formatted_Date
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.,2006-03-31 22:00:00+00:00
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.,2006-03-31 23:00:00+00:00
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.,2006-04-01 00:00:00+00:00
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.,2006-04-01 01:00:00+00:00
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.,2006-04-01 02:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94263,2016-05-09 19:00:00.000 +0200,Partly Cloudy,rain,19.972222,19.972222,0.40,9.4668,42,16.1000,0,1018.11,Partly cloudy throughout the day.,2016-05-09 17:00:00+00:00
94264,2016-05-09 20:00:00.000 +0200,Partly Cloudy,rain,17.816667,17.816667,0.46,3.8962,19,15.5526,0,1018.42,Partly cloudy throughout the day.,2016-05-09 18:00:00+00:00
94265,2016-05-09 21:00:00.000 +0200,Partly Cloudy,rain,13.938889,13.938889,0.67,8.0500,70,16.1000,0,1019.21,Partly cloudy throughout the day.,2016-05-09 19:00:00+00:00
94266,2016-05-09 22:00:00.000 +0200,Partly Cloudy,rain,12.733333,12.733333,0.77,8.0500,80,16.1000,0,1019.70,Partly cloudy throughout the day.,2016-05-09 20:00:00+00:00
94267,2016-05-09 23:00:00.000 +0200,Partly Cloudy,rain,13.038889,13.038889,0.69,3.2039,75,15.1823,0,1019.45,Partly cloudy throughout the day.,2016-05-09 21:00:00+00:00

In [12]:
df_train[["Formatted Date","Temperature (C)"]].sort_values(by="Formatted Date")

                      Formatted Date  Temperature (C)
2880   2006-01-01 00:00:00.000 +0100         0.577778
2881   2006-01-01 01:00:00.000 +0100         1.161111
2882   2006-01-01 02:00:00.000 +0100         1.666667
2883   2006-01-01 03:00:00.000 +0100         1.711111
2884   2006-01-01 04:00:00.000 +0100         1.183333
...                              ...              ...
89728  2016-12-31 19:00:00.000 +0100         0.488889
89729  2016-12-31 20:00:00.000 +0100         0.072222
89730  2016-12-31 21:00:00.000 +0100        -0.233333
89731  2016-12-31 22:00:00.000 +0100        -0.472222
89732  2016-12-31 23:00:00.000 +0100        -0.677778

[94268 rows x 2 columns]

In [13]:
df3 = pd.concat([df_train,df_test],axis=0,ignore_index=True)
df3

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Formatted_Date
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.,2006-03-31 22:00:00+00:00
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.,2006-03-31 23:00:00+00:00
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.,2006-04-01 00:00:00+00:00
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.,2006-04-01 01:00:00+00:00
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.,2006-04-01 02:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.,NaT
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.,NaT
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.,NaT
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.,NaT
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.,NaT

In [14]:
df_train['Formatted_Date']=pd.to_datetime(df_train['Formatted Date'],utc=True)

In [15]:
df_train.dtypes

Formatted Date                           object
Summary                                  object
Precip Type                              object
Temperature (C)                         float64
Apparent Temperature (C)                float64
Humidity                                float64
Wind Speed (km/h)                       float64
Wind Bearing (degrees)                    int64
Visibility (km)                         float64
Cloud Cover                               int64
Pressure (millibars)                    float64
Daily Summary                            object
Formatted_Date              datetime64[ns, UTC]
dtype: object

In [16]:
df_train.dropna(inplace=True)

In [17]:
df_train.drop('Formatted_Date',axis=1,inplace=True)

In [18]:
df_train['Formatted Date']=pd.to_datetime(df_train['Formatted Date'],utc=True)

In [19]:
df_train.dtypes

Formatted Date              datetime64[ns, UTC]
Summary                                  object
Precip Type                              object
Temperature (C)                         float64
Apparent Temperature (C)                float64
Humidity                                float64
Wind Speed (km/h)                       float64
Wind Bearing (degrees)                    int64
Visibility (km)                         float64
Cloud Cover                               int64
Pressure (millibars)                    float64
Daily Summary                            object
dtype: object

In [20]:
df_train.isnull().sum()

Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Cloud Cover                 0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

In [21]:
df_train.drop_duplicates(inplace=True)

In [22]:
df3.drop('Formatted_Date',axis=1,inplace=True)

In [23]:
df3.drop_duplicates(inplace=True)

In [24]:
df3.dtypes

Formatted Date               object
Summary                      object
Precip Type                  object
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)        int64
Visibility (km)             float64
Cloud Cover                   int64
Pressure (millibars)        float64
Daily Summary                object
dtype: object

In [25]:
df3.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Cloud Cover                   0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [26]:
df3['Temperature (C)'].corr(df3['Apparent Temperature (C)'])

0.9926254234649435

In [27]:
df3['Formatted Date']=pd.to_datetime(df3['Formatted Date'],utc=True)

In [28]:
import datetime as dt

In [29]:
df3['Date'] = df3['Formatted Date'].dt.date

In [30]:
df3

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Date
0,2006-03-31 22:00:00+00:00,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.,2006-03-31
1,2006-03-31 23:00:00+00:00,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.,2006-03-31
2,2006-04-01 00:00:00+00:00,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.,2006-04-01
3,2006-04-01 01:00:00+00:00,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.,2006-04-01
4,2006-04-01 02:00:00+00:00,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.,2006-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 17:00:00+00:00,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.,2016-09-09
96449,2016-09-09 18:00:00+00:00,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.,2016-09-09
96450,2016-09-09 19:00:00+00:00,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.,2016-09-09
96451,2016-09-09 20:00:00+00:00,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.,2016-09-09
96452,2016-09-09 21:00:00+00:00,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.,2016-09-09

In [31]:
t = df3['Date'].value_counts()

In [32]:
t=t[t!=24]

In [33]:
df3 = df3[~(df3['Date']==t.index[-1])]

In [34]:
df3[df3['Date']==t.index[0]].sort_values('Formatted Date')

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Date
89710,2016-12-31 00:00:00+00:00,Mostly Cloudy,snow,-1.161111,-4.394444,0.95,8.9999,203,7.3255,0,1020.59,Mostly cloudy throughout the day.,2016-12-31
89711,2016-12-31 01:00:00+00:00,Mostly Cloudy,snow,-1.488889,-4.750000,0.95,8.8711,207,7.9856,0,1020.48,Mostly cloudy throughout the day.,2016-12-31
89712,2016-12-31 02:00:00+00:00,Mostly Cloudy,snow,-1.822222,-5.116667,0.95,8.7906,204,6.6171,0,1020.41,Mostly cloudy throughout the day.,2016-12-31
89713,2016-12-31 03:00:00+00:00,Mostly Cloudy,snow,-2.077778,-5.444444,0.95,8.8711,193,4.4758,0,1020.40,Mostly cloudy throughout the day.,2016-12-31
89714,2016-12-31 04:00:00+00:00,Mostly Cloudy,snow,-2.177778,-5.688889,0.94,9.2736,175,5.5867,0,1020.46,Mostly cloudy throughout the day.,2016-12-31
89715,2016-12-31 05:00:00+00:00,Mostly Cloudy,snow,-2.050000,-5.694444,0.93,9.8210,165,3.6708,0,1020.59,Mostly cloudy throughout the day.,2016-12-31
89716,2016-12-31 06:00:00+00:00,Mostly Cloudy,snow,-1.655556,-5.350000,0.91,10.2718,163,4.1055,0,1020.75,Mostly cloudy throughout the day.,2016-12-31
89717,2016-12-31 07:00:00+00:00,Mostly Cloudy,snow,-1.016667,-4.766667,0.90,10.9802,167,5.7960,0,1020.90,Mostly cloudy throughout the day.,2016-12-31
89718,2016-12-31 08:00:00+00:00,Mostly Cloudy,snow,-0.194444,-3.977778,0.88,11.8335,173,4.8139,0,1020.98,Mostly cloudy throughout the day.,2016-12-31
89719,2016-12-31 09:00:00+00:00,Mostly Cloudy,rain,0.705556,-3.072222,0.87,12.6868,182,7.3899,0,1020.96,Mostly cloudy throughout the day.,2016-12-31
89720,2016-12-31 10:00:00+00:00,Mostly Cloudy,rain,1.550000,-2.194444,0.85,13.4274,190,8.0339,0,1020.83,Mostly cloudy throughout the day.,2016-12-31
89721,2016-12-31 11:00:00+00:00,Mostly Cloudy,rain,2.222222,-1.461111,0.84,13.8782,198,7.5992,0,1020.60,Mostly cloudy throughout the day.,2016-12-31
89722,2016-12-31 12:00:00+00:00,Mostly Cloudy,rain,2.622222,-0.983333,0.83,13.9909,205,9.8210,0,1020.32,Mostly cloudy throughout the day.,2016-12-31
89723,2016-12-31 13:00:00+00:00,Mostly Cloudy,rain,2.722222,-0.816667,0.83,13.7333,208,8.2593,0,1020.04,Mostly cloudy throughout the day.,2016-12-31
89724,2016-12-31 14:00:00+00:00,Mostly Cloudy,rain,2.538889,-0.933333,0.83,13.1215,207,8.2915,0,1019.81,Mostly cloudy throughout the day.,2016-12-31
89725,2016-12-31 15:00:00+00:00,Mostly Cloudy,rain,2.122222,-1.261111,0.83,12.2360,198,9.0160,0,1019.69,Mostly cloudy throughout the day.,2016-12-31
89726,2016-12-31 16:00:00+00:00,Mostly Cloudy,rain,1.583333,-1.694444,0.84,11.2056,182,6.7942,0,1019.70,Mostly cloudy throughout the day.,2016-12-31
89727,2016-12-31 17:00:00+00:00,Mostly Cloudy,rain,1.011111,-2.172222,0.85,10.3362,171,8.2110,0,1019.82,Mostly cloudy throughout the day.,2016-12-31
89728,2016-12-31 18:00:00+00:00,Mostly Cloudy,rain,0.488889,-2.644444,0.86,9.7566,167,8.0178,0,1020.03,Mostly cloudy throughout the day.,2016-12-31
89729,2016-12-31 19:00:00+00:00,Mostly Cloudy,rain,0.072222,-3.050000,0.88,9.4185,169,7.2450,0,1020.27,Mostly cloudy throughout the day.,2016-12-31
89730,2016-12-31 20:00:00+00:00,Mostly Cloudy,snow,-0.233333,-3.377778,0.89,9.2736,175,9.5795,0,1020.50,Mostly cloudy throughout the day.,2016-12-31
89731,2016-12-31 21:00:00+00:00,Mostly Cloudy,snow,-0.472222,-3.644444,0.91,9.2414,182,8.4042,0,1020.65,Mostly cloudy throughout the day.,2016-12-31
89732,2016-12-31 22:00:00+00:00,Mostly Cloudy,snow,-0.677778,-3.888889,0.92,9.2253,189,8.8711,0,1020.72,Mostly cloudy throughout the day.,2016-12-31

In [35]:
df3[df3['Date']==t.index[1]].sort_values('Formatted Date')

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Date
73896,2014-07-14 01:00:00+00:00,Mostly Cloudy,rain,17.177778,17.177778,0.90,3.2200,170,16.1000,0,1012.88,Partly cloudy throughout the day.,2014-07-14
73897,2014-07-14 02:00:00+00:00,Mostly Cloudy,rain,16.644444,16.644444,0.91,3.2200,220,15.1823,0,1012.61,Partly cloudy throughout the day.,2014-07-14
73898,2014-07-14 03:00:00+00:00,Mostly Cloudy,rain,15.894444,15.894444,0.94,5.8121,205,11.9140,0,1012.87,Partly cloudy throughout the day.,2014-07-14
73899,2014-07-14 04:00:00+00:00,Partly Cloudy,rain,16.094444,16.094444,0.93,3.0429,225,12.2521,0,1012.73,Partly cloudy throughout the day.,2014-07-14
73900,2014-07-14 05:00:00+00:00,Partly Cloudy,rain,17.738889,17.738889,0.90,7.5026,240,12.2521,0,1012.83,Partly cloudy throughout the day.,2014-07-14
73901,2014-07-14 06:00:00+00:00,Partly Cloudy,rain,21.655556,21.655556,0.72,3.3327,211,15.1823,0,1013.27,Partly cloudy throughout the day.,2014-07-14
73902,2014-07-14 07:00:00+00:00,Partly Cloudy,rain,22.666667,22.666667,0.63,3.1878,240,16.1000,0,1013.33,Partly cloudy throughout the day.,2014-07-14
73903,2014-07-14 08:00:00+00:00,Partly Cloudy,rain,24.844444,24.844444,0.51,4.6690,191,15.8263,0,1013.62,Partly cloudy throughout the day.,2014-07-14
73904,2014-07-14 09:00:00+00:00,Partly Cloudy,rain,24.844444,24.844444,0.48,7.7280,193,10.3523,0,1013.69,Partly cloudy throughout the day.,2014-07-14
73905,2014-07-14 10:00:00+00:00,Partly Cloudy,rain,26.066667,26.066667,0.47,4.6046,132,9.9820,0,1013.42,Partly cloudy throughout the day.,2014-07-14
73906,2014-07-14 11:00:00+00:00,Partly Cloudy,rain,27.177778,27.633333,0.51,3.2522,120,10.2557,0,1013.22,Partly cloudy throughout the day.,2014-07-14
73907,2014-07-14 12:00:00+00:00,Partly Cloudy,rain,27.600000,27.650000,0.45,2.9946,150,15.5526,0,1012.82,Partly cloudy throughout the day.,2014-07-14
73908,2014-07-14 13:00:00+00:00,Mostly Cloudy,rain,27.755556,27.661111,0.43,1.3041,50,16.1000,0,1012.21,Partly cloudy throughout the day.,2014-07-14
73909,2014-07-14 14:00:00+00:00,Mostly Cloudy,rain,27.266667,27.116667,0.41,0.1288,210,10.2557,0,1012.11,Partly cloudy throughout the day.,2014-07-14
73910,2014-07-14 15:00:00+00:00,Mostly Cloudy,rain,27.216667,27.366667,0.46,8.5491,78,10.3523,0,1011.84,Partly cloudy throughout the day.,2014-07-14
73911,2014-07-14 16:00:00+00:00,Mostly Cloudy,rain,24.233333,24.233333,0.57,19.0624,110,8.1305,0,1011.79,Partly cloudy throughout the day.,2014-07-14
73912,2014-07-14 17:00:00+00:00,Mostly Cloudy,rain,20.433333,20.433333,0.76,23.0069,119,9.9820,0,1012.93,Partly cloudy throughout the day.,2014-07-14
73913,2014-07-14 18:00:00+00:00,Mostly Cloudy,rain,20.100000,20.100000,0.75,12.0911,128,9.9820,0,1013.38,Partly cloudy throughout the day.,2014-07-14
73914,2014-07-14 19:00:00+00:00,Mostly Cloudy,rain,19.044444,19.044444,0.83,4.2826,266,9.9820,0,1013.52,Partly cloudy throughout the day.,2014-07-14
73915,2014-07-14 20:00:00+00:00,Mostly Cloudy,rain,18.983333,18.983333,0.83,5.9892,308,16.1000,0,1014.12,Partly cloudy throughout the day.,2014-07-14
73916,2014-07-14 21:00:00+00:00,Mostly Cloudy,rain,18.788889,18.788889,0.88,5.1520,315,14.3934,0,1014.06,Partly cloudy throughout the day.,2014-07-14
73917,2014-07-14 22:00:00+00:00,Mostly Cloudy,rain,18.333333,18.333333,0.90,6.6493,321,15.1823,0,1014.12,Partly cloudy throughout the day.,2014-07-14
73918,2014-07-14 23:00:00+00:00,Mostly Cloudy,rain,18.288889,18.288889,0.87,3.2039,91,15.1823,0,1014.31,Partly cloudy throughout the day.,2014-07-14

In [36]:
df3[df3['Date']==t.index[2]].sort_values('Formatted Date')

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Date
73874,2014-07-13 00:00:00+00:00,Partly Cloudy,rain,15.966667,15.966667,0.87,3.2200,199,15.1501,0,1011.23,Partly cloudy throughout the day.,2014-07-13
73875,2014-07-13 01:00:00+00:00,Partly Cloudy,rain,16.044444,16.044444,0.87,6.1180,171,16.1000,0,1011.02,Partly cloudy throughout the day.,2014-07-13
73876,2014-07-13 02:00:00+00:00,Partly Cloudy,rain,15.561111,15.561111,0.90,2.8336,153,15.1823,0,1011.20,Partly cloudy throughout the day.,2014-07-13
73877,2014-07-13 03:00:00+00:00,Mostly Cloudy,rain,16.144444,16.144444,0.90,5.6350,180,15.1823,0,1011.43,Partly cloudy throughout the day.,2014-07-13
73878,2014-07-13 04:00:00+00:00,Partly Cloudy,rain,16.072222,16.072222,0.87,0.0000,0,16.1000,0,1011.79,Partly cloudy throughout the day.,2014-07-13
73879,2014-07-13 05:00:00+00:00,Partly Cloudy,rain,17.788889,17.788889,0.89,4.6207,184,16.1000,0,1011.98,Partly cloudy throughout the day.,2014-07-13
73880,2014-07-13 06:00:00+00:00,Partly Cloudy,rain,21.111111,21.111111,0.73,2.0447,219,15.1823,0,1012.13,Partly cloudy throughout the day.,2014-07-13
73881,2014-07-13 07:00:00+00:00,Partly Cloudy,rain,23.816667,23.816667,0.62,4.7012,221,16.1000,0,1012.10,Partly cloudy throughout the day.,2014-07-13
73882,2014-07-13 08:00:00+00:00,Partly Cloudy,rain,26.016667,26.016667,0.50,4.7978,247,10.2557,0,1012.37,Partly cloudy throughout the day.,2014-07-13
73883,2014-07-13 09:00:00+00:00,Partly Cloudy,rain,25.000000,25.000000,0.47,6.4400,210,16.1000,0,1012.20,Partly cloudy throughout the day.,2014-07-13
73884,2014-07-13 10:00:00+00:00,Partly Cloudy,rain,24.683333,24.683333,0.49,6.3595,209,16.1000,0,1012.22,Partly cloudy throughout the day.,2014-07-13
73885,2014-07-13 11:00:00+00:00,Partly Cloudy,rain,24.300000,24.300000,0.50,6.2307,207,16.1000,0,1012.25,Partly cloudy throughout the day.,2014-07-13
73886,2014-07-13 12:00:00+00:00,Partly Cloudy,rain,23.850000,23.850000,0.53,6.0536,205,16.1000,0,1012.29,Partly cloudy throughout the day.,2014-07-13
73887,2014-07-13 13:00:00+00:00,Partly Cloudy,rain,23.350000,23.350000,0.56,5.8443,203,16.1000,0,1012.33,Partly cloudy throughout the day.,2014-07-13
73888,2014-07-13 14:00:00+00:00,Partly Cloudy,rain,22.811111,22.811111,0.58,5.6028,201,16.1000,0,1012.38,Partly cloudy throughout the day.,2014-07-13
73889,2014-07-13 15:00:00+00:00,Partly Cloudy,rain,22.244444,22.244444,0.62,5.3291,199,16.1000,0,1012.44,Partly cloudy throughout the day.,2014-07-13
73890,2014-07-13 16:00:00+00:00,Partly Cloudy,rain,21.655556,21.655556,0.65,5.0554,196,16.1000,0,1012.49,Partly cloudy throughout the day.,2014-07-13
73891,2014-07-13 17:00:00+00:00,Partly Cloudy,rain,21.061111,21.061111,0.68,4.7817,193,16.1000,0,1012.55,Partly cloudy throughout the day.,2014-07-13
73892,2014-07-13 18:00:00+00:00,Partly Cloudy,rain,20.461111,20.461111,0.72,4.5080,190,16.1000,0,1012.60,Partly cloudy throughout the day.,2014-07-13
73893,2014-07-13 19:00:00+00:00,Mostly Cloudy,rain,19.877778,19.877778,0.75,4.2504,187,16.1000,0,1012.66,Partly cloudy throughout the day.,2014-07-13
73894,2014-07-13 20:00:00+00:00,Mostly Cloudy,rain,19.311111,19.311111,0.78,4.0089,183,16.1000,0,1012.71,Partly cloudy throughout the day.,2014-07-13
73895,2014-07-13 21:00:00+00:00,Mostly Cloudy,rain,18.777778,18.777778,0.81,3.7996,180,16.1000,0,1012.76,Partly cloudy throughout the day.,2014-07-13

In [37]:
error = t.index
error

Index([2016-12-31, 2014-07-14, 2014-07-13, 2005-12-31], dtype='object', name='Date')

In [38]:
df3.drop("Cloud Cover",axis=1,inplace=True)

/var/folders/zl/763j_sh575dclj25sgxlp9vr0000gn/T/ipykernel_2331/219114345.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop("Cloud Cover",axis=1,inplace=True)

In [54]:
import pandas as pd
import numpy as np
from datetime import timedelta

def data_generator(xt, new_df, k):
    # Check necessary columns
    if "Formatted Date" not in new_df.columns:
        raise KeyError("'Formatted Date' column is missing in new_df.")
    if "Date" not in new_df.columns:
        raise KeyError("'Date' column is missing in new_df.")
    
    # Ensure 'Formatted Date' is datetime
    new_df["Formatted Date"] = pd.to_datetime(new_df["Formatted Date"], errors="coerce")
    
    # Ensure 'Hour' column exists
    if "Hour" not in new_df.columns:
        new_df["Hour"] = new_df["Formatted Date"].dt.hour
    
    # Filter rows for the given date
    g = new_df[new_df["Date"] == xt].copy()
    if g.empty:
        raise ValueError(f"No data found for the specified date: {xt}")
    
    if "Hour" not in g.columns:
        g["Hour"] = g["Formatted Date"].dt.hour
    
    # Generate missing hours
    q = pd.Series(range(0, 24))
    p = q[~(q.isin(g["Hour"].unique()))]
    md = {}
    pw = []

    for i in range(len(p)):
        gd = {}
        for j in g.columns[1:len(g.columns) - 2]:
            d_5 = [xt - timedelta(days=n) for n in range(1, k)]
            gen = new_df[(new_df["Date"].isin(d_5)) & (new_df["Hour"] == p.iloc[i])]

            if not gen.empty:
                if pd.api.types.is_object_dtype(g[j]):
                    gd[j] = gen[j].mode()[0] if not gen[j].mode().empty else None
                else:
                    gd[j] = gen[j].median()
            else:
                gd[j] = None

        md[str(xt) + " " + str(p.iloc[i])] = gd
        pw.append(p.iloc[i])

    fr = pd.DataFrame(md).T.reset_index(drop=True)
    col = fr.columns
    d1 = np.array(fr)
    mr = pd.DataFrame(d1, columns=col)
    mr["Hour"] = pw
    mr["Date"] = xt
    return mr

In [57]:
from datetime import timedelta

In [58]:
data = {
    "Date": pd.date_range("2024-01-01", periods=5).tolist() * 5,
    "Formatted Date": pd.date_range("2024-01-01", periods=25, freq="H"),
    "Value": np.random.randint(0, 100, size=25),
}
new_df = pd.DataFrame(data)

# Call the function
xt = pd.Timestamp("2024-01-02")
k = 3
result = data_generator(xt, new_df, k)
print(result)

        Formatted Date  Hour       Date
0  2024-01-01 00:00:00     0 2024-01-02
1                  NaT     2 2024-01-02
2                  NaT     3 2024-01-02
3                  NaT     4 2024-01-02
4  2024-01-01 05:00:00     5 2024-01-02
5                  NaT     7 2024-01-02
6                  NaT     8 2024-01-02
7                  NaT     9 2024-01-02
8  2024-01-01 10:00:00    10 2024-01-02
9                  NaT    12 2024-01-02
10                 NaT    13 2024-01-02
11                 NaT    14 2024-01-02
12 2024-01-01 15:00:00    15 2024-01-02
13                 NaT    17 2024-01-02
14                 NaT    18 2024-01-02
15                 NaT    19 2024-01-02
16 2024-01-01 20:00:00    20 2024-01-02
17                 NaT    22 2024-01-02
18                 NaT    23 2024-01-02

/var/folders/zl/763j_sh575dclj25sgxlp9vr0000gn/T/ipykernel_2331/592562823.py:3: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  "Formatted Date": pd.date_range("2024-01-01", periods=25, freq="H"),

In [59]:
l = data_generator(error[-2],df3,6)
l

/var/folders/zl/763j_sh575dclj25sgxlp9vr0000gn/T/ipykernel_2331/4276407505.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["Formatted Date"] = pd.to_datetime(new_df["Formatted Date"], errors="coerce")
/var/folders/zl/763j_sh575dclj25sgxlp9vr0000gn/T/ipykernel_2331/4276407505.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["Hour"] = new_df["Formatted Date"].dt.hour

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary,Hour,Date
0,Mostly Cloudy,rain,16.838889,16.838889,0.9,11.0607,260.0,15.8263,1006.74,Mostly cloudy throughout the day.,22,2014-07-13
1,Mostly Cloudy,rain,15.7,15.7,0.89,6.3756,225.0,14.6832,1006.64,Mostly cloudy throughout the day.,23,2014-07-13

In [60]:
o = data_generator(error[-2],df3,6)
o

/var/folders/zl/763j_sh575dclj25sgxlp9vr0000gn/T/ipykernel_2331/4276407505.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["Formatted Date"] = pd.to_datetime(new_df["Formatted Date"], errors="coerce")

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary,Hour,Date
0,Mostly Cloudy,rain,16.838889,16.838889,0.9,11.0607,260.0,15.8263,1006.74,Mostly cloudy throughout the day.,22,2014-07-13
1,Mostly Cloudy,rain,15.7,15.7,0.89,6.3756,225.0,14.6832,1006.64,Mostly cloudy throughout the day.,23,2014-07-13

In [61]:
p = data_generator(error[-3],df3,6)
p

/var/folders/zl/763j_sh575dclj25sgxlp9vr0000gn/T/ipykernel_2331/4276407505.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["Formatted Date"] = pd.to_datetime(new_df["Formatted Date"], errors="coerce")

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary,Hour,Date
0,Mostly Cloudy,rain,15.966667,15.966667,0.93,5.8121,241.0,11.914,1006.19,Mostly cloudy throughout the day.,0,2014-07-14

In [63]:
df3['Hour'] = df3['Formatted Date'].dt.hour

/var/folders/zl/763j_sh575dclj25sgxlp9vr0000gn/T/ipykernel_2331/3007175585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Hour'] = df3['Formatted Date'].dt.hour